### PR TITLE
Try getting the container's IP address

### PR DESCRIPTION
**Pull request by cotsog**
Recipe was found here => https://stackoverflow.com/a/20686101/213272

### CODE REVIEW

**Comment by global2alex** [comment]
Woah! I searched stackoverflow, never found this. This is great, thank you!

**Comment by global2alex** [comment]
Thank you very much, I will fix this and credit you for the full solution. Much appreciated.

**Comment by cotsog** [comment]
@global2alex No problem. Reading further, I believe that you will need to use the containers virtual host names since they are all on the same host. Some further reading: https://stackoverflow.com/questions/33021084/how-to-handle-ip-addresses-when-linking-docker-containers-with-each-other-using.

**Comment by global2alex** [comment]
#3

**Pull request closed without merging**
